sudo: false
language: clojure
lein: 2.8.1
jdk:
  - oraclejdk11

#before_install:
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"

script:
#  - "export DISPLAY=:99.0"
  - lein with-profile +test do version, test
